import "./globals.css";
import { Inter } from "next/font/google";
import {
  QueryClient,
  QueryClientProvider,
  dehydrate,
} from "@tanstack/react-query";
// import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // const queryClient = new QueryClient();
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <QueryClientProvider client={queryClient}> */}
        {children}
        {/* <ReactQueryDevtools initialIsOpen /> */}
        {/* </QueryClientProvider> */}
      </body>
    </html>
  );
}
